services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=database
    networks:
      - app_network
  database:
    image: postgres
    networks:
      - app_network

