services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
    networks:
      - app_network
  database:
    image: postgres
    networks:
      - app_network

