services:
  api:
    build: .
    ports:
      - "5433:5433"
    environment:
      - DB_HOST=database
    networks:
      - app_network
  database:
    image: postgres
    networks:
      - app_network

